import type { Project } from "@/content/schema";

export const projects: Project[] = [
  {
    id: "spyke-commerce",
    period: { from: "2024", ongoing: true },
    tech: [
      "Next.js",
      "React",
      "TypeScript",
      "ASP.NET Core",
      "Entity Framework Core",
      "SQL Server",
      "Microsoft Identity",
      "Material UI",
      "Tailwind CSS",
      "Azure",
      "GitHub Actions",
      "Cloudflare",
    ],
    images: [
      {
        id: "dashboard",
        src: "/images/projects/spyke-commerce-dashboard.webp",
        width: 2559,
        height: 1393,
        kind: "desktop",
      },
      {
        id: "signin",
        src: "/images/projects/spyke-commerce-login.webp",
        width: 2559,
        height: 1392,
        kind: "desktop",
      },
      {
        id: "products",
        src: "/images/projects/spyke-commerce-mobile.webp",
        width: 576,
        height: 1257,
        kind: "mobile",
      },
    ],
  },
  {
    id: "gnc-bulgaria",
    period: { from: "2025" },
    url: "https://www.gnc.bg",
    urlLabel: "gnc.bg",
    tech: [
      "Next.js",
      "React",
      "TypeScript",
      "ASP.NET Core",
      "SQL Server",
      "Azure",
      "Cloudflare",
    ],
    images: [
      {
        id: "storefront",
        src: "/images/projects/gnc-storefront.webp",
        width: 2559,
        height: 1398,
        kind: "desktop",
      },
      {
        id: "news",
        src: "/images/projects/gnc-mobile.webp",
        width: 581,
        height: 1255,
        kind: "mobile",
      },
    ],
  },
  {
    id: "bookapart",
    period: { from: "2025" },
    tech: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "shadcn/ui",
      "next-intl",
      "MDX",
      "Leaflet",
      "Azure Static Web Apps",
      "Azure Functions",
      "Azure Table Storage",
      "Azure Blob Storage",
    ],
    images: [
      {
        id: "home",
        src: "/images/projects/bookapart-home.webp",
        width: 2544,
        height: 1397,
        kind: "desktop",
      },
      {
        id: "stays",
        src: "/images/projects/bookapart-places.webp",
        width: 2559,
        height: 1392,
        kind: "desktop",
      },
      {
        id: "landmarks",
        src: "/images/projects/bookapart-landmarks.webp",
        width: 2559,
        height: 1397,
        kind: "desktop",
      },
      {
        id: "mobile",
        src: "/images/projects/bookapart-mobile.webp",
        width: 577,
        height: 1255,
        kind: "mobile",
      },
    ],
  },
  {
    id: "spyke-arbix",
    tech: [
      "Go",
      "React",
      "TypeScript",
      "PostgreSQL",
      "Redis",
      "NATS / JetStream",
      "WebSockets",
      "Docker",
    ],
    images: [],
  },
];
